language: python
python: "3.5"
cache: pip

env:
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pep8

addons:
    postgresql: "9.3"

install:
    - pip install tox
    - if [ "$TOXENV" = 'py34' ]; then pip install coveralls; fi

script:
    - tox -e $TOXENV

after_success:
    - if [ "$TOXENV" = 'py34' ]; then coveralls; fi

deploy:
    provider: pypi
    distributions: "sdist bdist_wheel"
    user: seantis
    password:
        secure: IzMdbimaGIQZK1nIOJB2dR2CLGgX5tU+IFvP4CZ+5ldCHGWUbug52/1Cd/y+Trtu5EjCGFYH5fUD1zeyrngpuijsO8QM3ypOY2MbmZlLKdjl5Illy7u5kjSmfi/LZR7k/qTZnj5we6dxznCLtO0kt30osE/6ZFL19kCwIpbtc7g=
    on:
        tags: true
        condition: $TOXENV = py34
