language: python
python: 3.4
env:
    - TOXENV=py34
    - TOXENV=pep8
install:
    - pip install tox==1.9.2
    - if [ "$TOXENV" = 'py34' ]; then pip install coveralls; fi
script:
    - tox -e $TOXENV
after_success:
    - if [ "$TOXENV" = 'py34' ]; then coveralls; fi
deploy:
    provider: pypi
    user: seantis
    distributions: "sdist bdist_wheel"
    password:
        secure: Qg6c9ejndUzc712oyqN1kzi6+zpWXY77xis6+V/QUzfkro7oh2TiFXzxVc1IJi4wUqJZJnJn2hjb0cfnB1K0VLMD9FMdHwlZpD68XIabziTRxEL/fuY01/CvX1/ytBK8nLlJPsIjco3f0Nu2b6aQQ0AzQ37q3+X1ABoPVppFI0w=
    on:
        tags: true
        condition: $TOXENV = py34
