cache: pip

matrix:
  include:
    - language: python
      python: "3.6"
      env: TOXENV=py36

    - language: python
      python: "3.6"
      env: TOXENV=pep8

addons:
  apt:
    packages:
      - libgnutls28-dev
      - libev-dev

install:
    - pip install tox
    - if [ "$TOXENV" = 'py36' ]; then pip install coveralls; fi

script:
    - tox -e $TOXENV

after_success:
    - if [ "$TOXENV" = 'py36' ]; then coveralls; fi

deploy:
    provider: pypi
    user: seantis
    distributions: "sdist bdist_wheel"
    password:
        secure: Qg6c9ejndUzc712oyqN1kzi6+zpWXY77xis6+V/QUzfkro7oh2TiFXzxVc1IJi4wUqJZJnJn2hjb0cfnB1K0VLMD9FMdHwlZpD68XIabziTRxEL/fuY01/CvX1/ytBK8nLlJPsIjco3f0Nu2b6aQQ0AzQ37q3+X1ABoPVppFI0w=
    on:
        tags: true
        condition: $TOXENV = py36
