fixes:
  - "app/lib/python3.12/site-packages/::src/"
coverage:
  status:
    project:
      default:
        informational: true
comment:
  layout: "header, files, footer"
  hide_project_coverage: false
  after_n_builds: 8
