version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1-amd64
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - data01:/usr/share/elasticsearch/data

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '8081:80'
      - '1025:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev

volumes:
  data01:
    driver: local
  smtp4dev-data:
    driver: local
