version: '3'
services:
    # For trying out different postgres versions.
    # Use postgresql://postgres:postgres@localhost:5444/onegov in onegov.yml
    # Note that this won't work with tests and "onegov-core transfer"!
    # 
    # postgres:
    #     image: postgres:14
    #     environment:
    #         - POSTGRES_PASSWORD=postgres
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_DB=onegov
    #     ports:
    #         - "5444:5432"

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1-amd64
        container_name: elasticsearch
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - bootstrap.memory_lock=true
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - data01:/usr/share/elasticsearch/data

    smtp4dev:
        image: rnwood/smtp4dev:latest
        restart: always
        ports:
            - "8081:80"
            - "1025:25"
            - "143:143"
        volumes:
            - smtp4dev-data:/smtp4dev

    d3renderer:
        image: node
        command: sh -c "rm -rf d3-renderer && git clone https://github.com/seantis/d3-renderer.git && cd d3-renderer && npm install && ./node_modules/.bin/phantomjs server.js"
        environment:
            - OPENSSL_CONF=/etc/ssl
        working_dir: /app
        ports:
            - "1337:1337"


volumes:
    data01:
        driver: local
    smtp4dev-data:
        driver: local
