[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
log_level = "INFO"
testpaths = ["tests"]
timeout = 300

[tool.coverage.run]
data_file = "/tmp/.coverage"
include = ["*/onegov/*"]
omit = ["*/tests/*"]

[tool.coverage.report]
ignore_errors = true

[tool.mypy]
python_version = "3.10"
follow_imports = "silent"
namespace_packages = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/src"

[tool.bandit]
exclude_dirs = ["*/tests/*", "*/**/upgrade.py"]
skips = [
    "B101",  # ignore asserts
]
