[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
log_level = "INFO"
testpaths = ["tests"]
timeout = 300

[tool.coverage.run]
data_file = "/tmp/.coverage"
include = ["*/onegov/*"]
omit = ["*/tests/*"]

[tool.coverage.report]
ignore_errors = true
exclude_lines = [
    "pragma: no cover",
    "pragma: unreachable",
    "assert_never[(]",
    "@overload",
    "raise NotImplementedError",
    "raise AssertionError[(].unreachable.[)]",
    "if TYPE_CHECKING:",
    "if __name__ == .__main__."
]

[tool.mypy]
python_version = "3.10"
follow_imports = "silent"
namespace_packages = true
explicit_package_bases = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
plugins = "sqlmypy"
mypy_path = "$MYPY_CONFIG_FILE_DIR/src:$MYPY_CONFIG_FILE_DIR/stubs"

[[tool.mypy.overrides]]
# more strict rules for fully typed modules
module = [
    "onegov.activity.*",
    "onegov.agency.*",
    "onegov.api.*",
    "onegov.async_http.*",
    "onegov.ballot.*",
    "onegov.chat.*",
    "onegov.core.*",
    "onegov.directory.*",
    "onegov.election_day.*",
    "onegov.event.*",
    "onegov.file.*",
    "onegov.form.*",
    "onegov.foundation.*",
    "onegov.foundation6.*",
    "onegov.gazette.*",
    "onegov.gever.*",
    "onegov.gis.*",
    "onegov.newsletter.*",
    "onegov.notice.*",
    "onegov.onboarding.*",
    "onegov.org.*",
    "onegov.page.*",
    "onegov.pas.*",
    "onegov.pay.*",
    "onegov.pdf.*",
    "onegov.people.*",
    "onegov.qrcode.*",
    "onegov.quill.*",
    "onegov.recipient.*",
    "onegov.reservation.*",
    "onegov.server.*",
    "onegov.shared.*",
    "onegov.stepsequence.*",
    "onegov.ticket.*",
    "onegov.town6.*",
    "onegov.user.*",
    "onegov.websockets.*",
    "onegov.wtfs.*"
]
warn_unreachable = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
strict_equality = true
extra_checks = true

[[tool.mypy.overrides]]
# ignore missing imports for packages that have no stubs available
module = [
    "bjoern.*",
    "blinker.*",
    "cssutils.*",
    "elasticsearch_dsl.*",
    "docxtpl.*",
    "dill.*",
    "dukpy.*",
    # FIXME: is this still faster than stdlib? it's not maintained
    "fastcache.*",
    "genshi.*",
    "icalendar.*",
    # FIXME: Do we really need this? We have this implemented ourselves
    #        in OCQMS, so we could just copy that code over... plus the
    #        standard lib technically supports some ISO-8601 formats as well
    "isodate.*",
    "kerberos.*",
    # TODO: Consider switching to fasttext-langdetect
    #       langdetect is really, really slow by comparison...
    "langdetect.*",
    "lazy_object_proxy.*",
    "mistletoe.*",
    "msal.*",
    "pdfdocument.*",
    # FIXME: We only use this to convert a PDF to an XObject and then
    #        embed it as a reportlab Flowable. I think we could implement
    #        this using just pypdf, having multiple PDF parsers just for
    #        this one use-case seems bad
    "pdfrw.*",
    "pdftotext.*",
    "pglast.*",
    "purl.*",
    "pyquery.*",
    "qrbill.*",
    "qrcode.*",
    "rcssmin.*",
    "reportlab.*",
    "rjsmin.*",
    # TODO: Writing stubs for this would probably be really quick
    #       but do we actually have a good use-case for this or
    #       could we just do the sort at the end?
    "sortedcontainers.*",
    "sqlparse.*",
    "svglib.*",
    "stdnum.*",
    "transaction.*",
    "ua_parser.*",
    "urlextract.*",
    "webassets.*",
    "webtest.*",
    "xlrd.*",
    "xlsxwriter.*",
    "xtermcolor.*",
    "yubico_client.*",
    "zope.*"
]
ignore_missing_imports = true


[tool.bandit]
exclude_dirs = [
    "tests",
    "*/**/upgrade.py",
    "*/**/upgrades.py"
]
skips = [
    # ignore asserts
    "B101",
    # ignore pickle (SEA-1030)
    "B301",
    "B403",
    # ignore XML (SEA-1031)
    "B314",
    "B320",
    "B405",
    "B410",
    # ignore subprocesses (SEA-1032)
    "B404",
    "B602",
    "B603",
    "B605",
    "B607",
    # ignore temp directory (SEA-1033)
    "B108"
]
