language: python
python: "3.4"
cache: pip

env:
    - TOXENV=py34
    - TOXENV=pep8
install:
    - pip install tox
    - if [ "$TOXENV" = 'py34' ]; then pip install coveralls; fi
script:
    - tox -e $TOXENV
after_success:
    - if [ "$TOXENV" = 'py34' ]; then coveralls; fi
