#!/usr/bin/env python3
# HACK: We should just include cat in our ci-agent container, so we
#       use it, but for now we just re-implement it using python, since
#       we have access to that in the ci-agent container
import argparse
import sys


parser = argparse.ArgumentParser()
parser.add_argument('file', type=argparse.FileType('r'))

args = parser.parse_args()
sys.stdout.write(args.file.read())
