steps:

  # build the container…
  - command: "build-container"
    label: "Building"

    agents:
      - queue=builder

    env:
      CONTAINER: "onegov-cloud:head"

  - wait

  # run the python tests
  - command: "test-container"
    label: "Testing"

    parallelism: 4

    agents:
      - queue=generic
      - cpu=2
      - ram=4096

    env:
      CONTAINER: "onegov-cloud:head-${BUILDKITE_COMMIT:0:10}"
      CONTAINER_TEST_SCRIPT: ".buildkite/test"
      CONTAINER_TEST_ARG: "container"
