steps:

  # build the container…
  - command: "build-container"
    label: "Building"

    agents:
      - queue=builder

    env:
      CONTAINER: "onegov-cloud:head"

  - wait

  # check linting
  - command: "test-container"
    label: "Linting"

    agents:
      - queue=generic
      - ram=2048

    env:
      CONTAINER: "onegov-cloud:head-${BUILDKITE_COMMIT:0:10}"
      CONTAINER_TEST_SCRIPT: ".buildkite/lint"
      CONTAINER_TEST_ARG: "container"

  # run the javascript tests
  - command: "test-container"
    label: "Jesting"

    agents:
      - queue=generic

    if: build.message =~ /jest/

    env:
      CONTAINER: "onegov-cloud:head-${BUILDKITE_COMMIT:0:10}"
      CONTAINER_TEST_SCRIPT: ".buildkite/jest 1"
      CONTAINER_TEST_ARG: "container"

  # run the python tests
  - command: "test-container"
    label: "Testing"

    parallelism: 4

    agents:
      - queue=generic
      - cpu=2
      - ram=4096

    env:
      CONTAINER: "onegov-cloud:head-${BUILDKITE_COMMIT:0:10}"
      CONTAINER_TEST_SCRIPT: ".buildkite/test 1"
      CONTAINER_TEST_ARG: "container"

  # build the docs if possible (fails are ignored, only on master)
  - command: "test-container"
    label: "Publishing docs"

    agents:
      - queue=generic
      - ram=4096

    soft_fail:
      - exit_status: 1

    env:
      CONTAINER: "onegov-cloud:head-${BUILDKITE_COMMIT:0:10}"
      CONTAINER_TEST_SCRIPT: ".buildkite/docs"

    branches: "master"
