#!/usr/bin/env bash
set -euo pipefail

# switch to virtual environment
cd /app

# shellcheck disable=SC1091
source bin/activate

cd /app/src

echo "--- Installing docs dependencies"
install-packages curl make zip

# prefer our devpi instance (extra takes precedence in uv)
export UV_EXTRA_INDEX_URL="${PIP_INDEX_URL}"

pip install --upgrade uv
uv pip install '.[docs]'

echo "--- Building docs"
cd docs
make html

echo "--- Packaging docs"
cd _build/html
zip -r docs.zip .

echo "--- Deploying docs"
curl -H "Content-Type: application/zip" \
     -H "Authorization: Bearer $NETLIFY_TOKEN" \
     --data-binary "@docs.zip" \
     https://api.netlify.com/api/v1/sites/onegov-cloud-docs.netlify.com/deploys
