#!/usr/bin/env bash
set -euo pipefail

# automatically open the log output group if there's an error
trap 'echo "^^^ +++"' ERR

echo "--- Installing node"
pip install nodeenv
node=$(nodeenv --list 2>&1 | tr '\t' '\n' | grep -E '^12' | tail -n 1)

nodeenv --node="$node" /tmp/node

echo "--- Installing dependencies"
cd /app/src/tests/js
/tmp/node/bin/npm install jest jsdom

echo "--- Writing config"
echo "{\"scripts\":{\"test\": \"jest\"}}" > package.json

echo "--- Running Jest"
/tmp/node/bin/npm test
