#!/usr/bin/env bash
set -euo pipefail

# automatically open the log output group if there's an error
trap 'echo "^^^ +++"' ERR

echo "--- Installing node"
pip install nodeenv
node=$(nodeenv --list 2>&1 | tr '\t' '\n' | grep -E '^12' | tail -n 1)

nodeenv --node="$node" /tmp/node

echo "--- Installing dependencies"

# only switch to container src directory if we want to test
# the container, rather than just the source tree
if [[ "${CONTAINER_TEST_ARG:-}" = "container" ]]; then
    cd /app/src/tests/js
else
    # node has reduced privileges so we need to copy the source tree
    cp -r . /tmp/node/src
    cd /tmp/node/src/tests/js
fi

/tmp/node/bin/npm install

echo "--- Running Jest"
/tmp/node/bin/npm test
