#!/usr/bin/env bash
set -euo pipefail

# automatically open the log output group if there's an error
trap 'echo "^^^ +++"' ERR

# we need these because mypy needs to install onegov[mypy]
# shellcheck disable=SC2086
echo "--- Installing requirements"
[ -f /etc/apt/preferences ] && rm /etc/apt/preferences
install-packages \
    wget \
    apparmor \
    curl \
    git-core \
    postgresql \
    redis \
    openjdk-8-jre-headless \
    gcc \
    libc-dev \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libdrm2 \
    libgbm1 \
    libnspr4 \
    libnss3 \
    libu2f-udev \
    libvulkan1 \
    libx11-xcb1 \
    libxcb-dri3-0 \
    libxshmfence1 \
    libxss1 \
    xdg-utils

echo "--- Creating virtual environment"

# switch to virtual environment
# shellcheck disable=SC1091
source /app/bin/activate

echo "--- Installing prerequisites"
echo "$(python --version)"

# only switch to container src directory if we want to test
# the container, rather than just the source tree
if [[ "${CONTAINER_TEST_ARG:-}" = "container" ]]; then
    cd /app/src
fi

# prefer our devpi instance (extra takes precedence in uv)
export UV_EXTRA_INDEX_URL="${PIP_INDEX_URL}"

pip install --upgrade uv
uv pip install '.[mypy]' GitPython flake8 flake8-bugbear flake8-pyi bandit[toml] --quiet

echo "--- Linting"
flake8 src/ tests/ stubs/

echo "--- Check security issues"
bandit --recursive --configfile pyproject.toml src/

echo "--- Static type checking"
mypy -p onegov
