#!/usr/bin/env bash
set -euo pipefail

# automatically open the log output group if there's an error
trap 'echo "^^^ +++"' ERR

echo "--- Installing prerequisites"
pip install flake8

echo "--- Linting"
flake8 src/ tests/
