steps:

  # choose the pipeline we want to use…
  - command: start-pipeline
    label: "Running tests on built container"

    agents:
      - queue=builder

    env:
      PIPELINE_CONFIG: ".buildkite/container-pipeline.yml"

    if: |
      build.branch =~ /^release-/ ||
      build.message =~ /\[test-container\]/i

  - command: start-pipeline
    label: ":pipeline: Running tests on generic container"

    env:
      PIPELINE_CONFIG: ".buildkite/generic-pipeline.yml"

    agents:
      - queue=builder

    if: |
      build.branch !~ /^release-/ &&
      build.message !~ /\[test-container\]/i

  - wait

  # if this is a release, publish the container
  - command: "publish-container"
    label: "Publishing"
    branches: "release-*"

    agents:
      - queue=builder

    env:
      CONTAINER: "onegov-cloud:head"
