steps:

  # we can save quite a bit of compute, with a separate lint step
  - command: "test-container"
    label: "Linting"

    agents:
      - queue=generic

    env:
      CONTAINER: "onegov-cloud:head"
      CONTAINER_TEST_SCRIPT: ".buildkite/lint"

  - wait

  # run the javascript tests
  # - command: "test-container"
  #   label: "Jesting"
  #
  #   agents:
  #     - queue=generic
  #
  #   env:
  #     CONTAINER: "onegov-cloud:head"
  #     CONTAINER_TEST_SCRIPT: ".buildkite/jest"

  - wait

  # build the container…
  - command: "build-container"
    label: "Building"

    agents:
      - queue=builder

    env:
      CONTAINER: "onegov-cloud:head"

  - wait

  # …before running tests
  - command: "test-container"
    label: "Testing"

    parallelism: 4

    agents:
      - queue=generic
      - cpu=2
      - ram=4096

    env:
      CONTAINER: "onegov-cloud:head"
      CONTAINER_TEST_SCRIPT: ".buildkite/test"

  # build the docs if possible (fails are ignored, only on master)
  - command: "test-container"
    label: "Publishing docs"

    agents:
      - queue=generic

    soft_fail:
      - exit_status: 1

    env:
      CONTAINER: "onegov-cloud:head"
      CONTAINER_TEST_SCRIPT: ".buildkite/docs"

    branches: "master"

  - wait

  # if this is a release, publish the container
  - command: "publish-container"
    label: "Publishing"
    branches: "release-*"

    agents:
      - queue=builder

    env:
      CONTAINER: "onegov-cloud:head"
