cache: pip

matrix:
  include:
    - language: python
      python: "3.6"
      env: TOXENV=py36

    - language: python
      python: "3.6"
      env: TOXENV=pep8

addons:
    postgresql: "9.6"
    apt:
      packages:
        - ghostscript
        - libpoppler-cpp-dev

install:
    - pip install tox
    - if [ "$TOXENV" = 'py36' ]; then pip install coveralls; fi

script:
    - tox -e $TOXENV

after_success:
    - if [ "$TOXENV" = 'py36' ]; then coveralls; fi

deploy:
    provider: pypi
    distributions: "sdist bdist_wheel"
    user: seantis
    password:
        secure: iQAXrd2tWk/bn9U9HqxlGB5W8ETcmsnwJtraXfAFSha8Y8BCjIsdp5GyTQjSJJP1rraBgjELHeNmFeeEOqK8qlO5I6Lz8qvEV7b9sQD3bIYMc1jJWl7FLLyBGWKTHprnJ094RSSlNoU+tNZgA3xSosNpfbaSJSEpROF/+GiBDjE=
    on:
        tags: true
        condition: $TOXENV = py36
