cache: pip

matrix:
  include:
    - language: python
      python: "3.6"
      env: TOXENV=py36

    - language: python
      python: "3.6"
      env: TOXENV=pep8

addons:
  postgresql: "9.6"
  apt:
        packages:
            - ghostscript

install:
    - pip install tox
    - if [ "$TOXENV" = 'py36' ]; then pip install coveralls; fi

script:
    - tox -e $TOXENV

after_success:
    - if [ "$TOXENV" = 'py36' ]; then coveralls; fi
    - 'if [ "$TOXENV" = "py36" ]; then $TRAVIS_BUILD_DIR/.tox/py36/bin/pip freeze | sed -r "s/^-e git.*?egg=([a-z\._]+)$/\1==${TRAVIS_TAG:1}/g" > $TRAVIS_BUILD_DIR/requirements.txt; fi'
    - if [ "$TOXENV" = 'py36' ]; then cat requirements.txt; fi

deploy:

  - provider: releases
    api_key:
        secure: ""
    file: requirements.txt
    skip_cleanup: true
    on:
        tags: true
        condition: $TOXENV = py36

  - provider: pypi
    distributions: "sdist bdist_wheel"
    user: seantis
    password:
        secure: ""
    on:
        tags: true
        condition: $TOXENV = py36
