from typing_extensions import Self

from depot.fields.interfaces import DepotFileInfo
from depot.io.interfaces import _FileContent, _UUIDStr, FileStorage, StoredFile

class UploadedFile(DepotFileInfo):
    def process_content(self, content: _FileContent, filename: str | None = None, content_type: str | None = None) -> None: ...
    def store_content(self, content: _FileContent, filename: str | None = None, content_type: str | None = None) -> tuple[str, _UUIDStr]: ...
    def encode(self) -> str: ...
    @classmethod
    def decode(cls, data: str) -> Self: ...
    @property
    def url(self) -> str: ...
    @property
    def depot(self) -> FileStorage: ...
    @property
    def file(self) -> StoredFile: ...
