from collections.abc import Sequence
from typing import Any

from morepath.request import Request
from webob.response import Response

DEFAULT_NAME: str

def publish(request: Request) -> Response: ...
def resolve_model(request: Request) -> Any | None: ...
def resolve_response(obj: object, request: Request) -> Response: ...
def get_view_name(stack: Sequence[str]) -> str | None: ...
