from collections.abc import Callable
from typing import Any

class SettingRegistry:
    def register_setting(self, section_name: str, setting_name: str, func: Callable[[], object]) -> None: ...
    def __getattr__(self, name: str) -> SettingSection: ...

class SettingSection:
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
