from typing import Any as Incomplete
# FIXME: I don't know what we use this for, it doesn't seem helpful, since
#        the only class that derives from it doesn't implement _coerce...
class ScalarCoercible:
    def _coerce(self, value: Incomplete) -> Incomplete: ...
    def coercion_listener(self, target: Incomplete, value: Incomplete, oldvalue: Incomplete, initiator: Incomplete) -> Incomplete: ...
