# FIXME: I don't know what we use this for, it doesn't seem helpful, since
#        the only class that derives from it doesn't implement _coerce...
class ScalarCoercible:
    def _coerce(self, value): ...
    def coercion_listener(self, target, value, oldvalue, initiator): ...
