language: python
python: "3.4"
env:
    - TOXENV=py34 ES_BINARY=/tmp/elasticsearch/bin/elasticsearch ES_URL=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-2.2.0.tar.gz
    - TOXENV=pep8 ES_URL=no


install:
    - pip install tox==1.9.2
    - if [ "$TOXENV" = 'py34' ]; then pip install coveralls; fi
    - if [ "$ES_URL" != 'no' ]; mkdir /tmp/elasticsearch; fi
    - if [ "$ES_URL" != 'no' ]; wget -O - "$ES_URL" | tar xz --directory=/tmp/elasticsearch --strip-components=1; fi

script:
    - tox -e $TOXENV

after_success:
    - if [ "$TOXENV" = 'py34' ]; then coveralls; fi
    - 'if [ "$TOXENV" = "py34" ]; then $TRAVIS_BUILD_DIR/.tox/py34/bin/pip freeze | sed -r "s/^-e git.*?egg=([a-z\._]+)$/\1==${TRAVIS_TAG:1}/g" > $TRAVIS_BUILD_DIR/requirements.txt; fi'
    - if [ "$TOXENV" = 'py34' ]; then cat requirements.txt; fi

deploy:

  - provider: releases
    api_key:
        secure: "LfZUmiNfEnydbF6XYGH45GUrj26IzkT6qNvYNN0zglrd7dEMzUcgA2PjOk/89Nia2TV63SedwLrG2fhHT1Owi0mU8NrNrEoBWbboWoQ7Tclw35snDdGUjib4zK4BkA99Exd2wQBfygtPSmlb9pTzppKhs0v4UtnWWL3e8TNQAsc="
    file: requirements.txt
    skip_cleanup: true
    on:
        tags: true
        condition: $TOXENV = py34

  - provider: pypi
    distributions: "sdist bdist_wheel"
    user: seantis
    password:
        secure: "TfCasvV0u5OHsD1uO74Tn7IqkVM271WzmRuI61uIAY9AyC+IBRfso/Ch8o+D7dw12BVCeWX6g89Vb1Z+FcsxRr7aeBbPZj9zg8duo/oyov6GpJivB8qbAIKGuKy5OmQTAjGE9DxncY0/XB3GtJDqzxiEu8t5rEKG6usOmGBV/G0="
    on:
        tags: true
        condition: $TOXENV = py34
