language: python
python: "3.5"
cache: pip

env:
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pep8

addons:
  postgresql: "9.3"

install:
    - pip install tox
    - if [ "$TOXENV" = 'py34' ]; then pip install coveralls; fi

script:
    - tox -e $TOXENV

after_success:
    - if [ "$TOXENV" = 'py34' ]; then coveralls; fi
    - 'if [ "$TOXENV" = "py34" ]; then $TRAVIS_BUILD_DIR/.tox/py34/bin/pip freeze | sed -r "s/^-e git.*?egg=([a-z\._]+)$/\1==${TRAVIS_TAG:1}/g" > $TRAVIS_BUILD_DIR/requirements.txt; fi'
    - if [ "$TOXENV" = 'py34' ]; then cat requirements.txt; fi

deploy:

  - provider: releases
    api_key:
        secure: ""
    file: requirements.txt
    skip_cleanup: true
    on:
        tags: true
        condition: $TOXENV = py34

  - provider: pypi
    distributions: "sdist bdist_wheel"
    user: seantis
    password:
        secure: ""
    on:
        tags: true
        condition: $TOXENV = py34
