cache: pip

matrix:
  include:
    - language: python
      python: "3.6"
      env: TOXENV=py36

    - language: python
      python: "3.6"
      env: TOXENV=pep8

addons:
    postgresql: "9.6"
    apt:
        packages:
            - ghostscript

install:
    - pip install tox
    - if [ "$TOXENV" = 'py36' ]; then pip install coveralls; fi

script:
    - tox -e $TOXENV

after_success:
    - if [ "$TOXENV" = 'py36' ]; then coveralls; fi
    - 'if [ "$TOXENV" = "py36" ]; then $TRAVIS_BUILD_DIR/.tox/py36/bin/pip freeze | sed -r "s/^-e git.*?egg=([a-z\._]+)$/\1==${TRAVIS_TAG:1}/g" > $TRAVIS_BUILD_DIR/requirements.txt; fi'
    - if [ "$TOXENV" = 'py36' ]; then cat requirements.txt; fi

deploy:

  - provider: releases
    api_key:
        secure: "Z7Br132se9vnqUycNumQm9Zh6R05v86UIwmcWXnPywDnx/D1tjrVsyLkfIa4UEt7hKQAWG6+3HMuHOuVJz9Wg1uzb3yLite+oS1CqHEbB9/AJb7gfmvywJY1OeLLLPCUglkpxoITWcxVYuK2rYmRb6txQqj8GTR5k1z5A4j6EU2glaUZa0fnwyxSPxroV5xOHqj77zx1nYVssAfKlCzC0K5UEiBPjCLCWnPwCu+Av3aGTKK8V2K9wEX84tjxm9Vd2n1bEGnARI0h5OISwnefYoSHyoRopoE5nQxon+wGRKuRENMW45LAGgW50eKu19wwZqxOv0nfmu6jH6elIcfQu4jKLn8rawaH8YR3QMjGwQzuGknjlAisWW/U21mx2bptYcS3NmxWVtqmgfOmwuGdvZvS0Wixenjic3SmBHJy+ukhAGcTD8HIkyldD1xQIV7EH1kwRjBU2FOoIosroTTlggIi57xDdRDkf+OW3TlG74/o39yl21FWHfRuejqO6jcjBwDsj55LsIBvvVy8SQRw4HemdWWsrUaG9gK/8Dly5ahTOHc6W4OyWN9s2+XbCPPpMr8MqB4FxhRcaL0euSXzLd3CZ/wmYJr2dafdh68d9kOFwS7I8O3BOfWWsxrJK9BvWgWDmCPiKrNi9G2Pc+IqBxWa+p+U4Y1CRL7L3YNJmP8="
    file: requirements.txt
    skip_cleanup: true
    on:
        tags: true
        condition: $TOXENV = py36

  - provider: pypi
    distributions: "sdist bdist_wheel"
    user: seantis
    password:
        secure: "aVqJCW/anipZ+K/oAM/6LdmuIRSUF8tdmkCyyH0VofLyH+FJtiq/dfr+zxdb0NkTYrbVgt2YdmzWuudyW/gWTBnXeaNd6YAVINMhbf2N01ltYanKmgXoD40f/tc3cJKrZona2+F7Re0DmryMuw9dU8ojZYdY0npYZk13GaLhkwIdVjkncOEVwQGB7x4zQaC4ednk/uXkrfqdvO7oFS9y3mLR9XHzS6FcSY8nOpGISz2mJUSEbJd82bBcBGDffWD1o6Ru4FWrwtTssfaxCWL8IiGFxFMk15IV5ET4xNb5wW0ObUwVdkw4nRF5FtjvKd7evdNwgymTJuJ3+iNHLJp72IoKTMEyWFgpJ1TnyVRpYaH5fm2vBLlKr2T4HhUPFnokUlln2SvcAPT2WxllTsnqcy1UYSC2owhMs8OHA/V6biwzdQPHpRaZ1YikfqXbldgrdhN/dbd6j3K+p0AmeabeOcr1e5YjHo9Z/KCP0yW3d3OS4nVSta5ZGEg7w7avRCi9MFHRDQkVx5kb0ClctsQL02fxPJGd/DKfHrO9mQV2pssJl11tpA/yFyqi/F27l6PUqRYa9LWLWkdUaOudc0zI23R3EP5sSjIxXh2ye9zQ6NKA5onXF6Dkr0dK96H39YNSlpZ54eFhnmvgn8IniKmoKtHoUvbtTG97ijszDWQVERY="
    on:
        tags: true
        condition: $TOXENV = py36
