language: python
python: "3.5"
cache: pip

env:
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pep8

addons:
  postgresql: "9.3"

install:
    - pip install tox
    - if [ "$TOXENV" = 'py34' ]; then pip install coveralls; fi

script:
    - tox -e $TOXENV

after_success:
    - if [ "$TOXENV" = 'py34' ]; then coveralls; fi
    - 'if [ "$TOXENV" = "py34" ]; then $TRAVIS_BUILD_DIR/.tox/py34/bin/pip freeze | sed -r "s/^-e git.*?egg=([a-z\._]+)$/\1==${TRAVIS_TAG:1}/g" > $TRAVIS_BUILD_DIR/requirements.txt; fi'
    - if [ "$TOXENV" = 'py34' ]; then cat requirements.txt; fi

deploy:

  - provider: releases
    api_key:
        secure: ""
    file: requirements.txt
    skip_cleanup: true
    on:
        tags: true
        condition: $TOXENV = py34

  - provider: pypi
    distributions: "sdist bdist_wheel"
    user: seantis
    password:
        secure: "aVqJCW/anipZ+K/oAM/6LdmuIRSUF8tdmkCyyH0VofLyH+FJtiq/dfr+zxdb0NkTYrbVgt2YdmzWuudyW/gWTBnXeaNd6YAVINMhbf2N01ltYanKmgXoD40f/tc3cJKrZona2+F7Re0DmryMuw9dU8ojZYdY0npYZk13GaLhkwIdVjkncOEVwQGB7x4zQaC4ednk/uXkrfqdvO7oFS9y3mLR9XHzS6FcSY8nOpGISz2mJUSEbJd82bBcBGDffWD1o6Ru4FWrwtTssfaxCWL8IiGFxFMk15IV5ET4xNb5wW0ObUwVdkw4nRF5FtjvKd7evdNwgymTJuJ3+iNHLJp72IoKTMEyWFgpJ1TnyVRpYaH5fm2vBLlKr2T4HhUPFnokUlln2SvcAPT2WxllTsnqcy1UYSC2owhMs8OHA/V6biwzdQPHpRaZ1YikfqXbldgrdhN/dbd6j3K+p0AmeabeOcr1e5YjHo9Z/KCP0yW3d3OS4nVSta5ZGEg7w7avRCi9MFHRDQkVx5kb0ClctsQL02fxPJGd/DKfHrO9mQV2pssJl11tpA/yFyqi/F27l6PUqRYa9LWLWkdUaOudc0zI23R3EP5sSjIxXh2ye9zQ6NKA5onXF6Dkr0dK96H39YNSlpZ54eFhnmvgn8IniKmoKtHoUvbtTG97ijszDWQVERY="
    on:
        tags: true
        condition: $TOXENV = py34
