#!/usr/bin/env python

import os
import re

import click

base = os.path.join(os.getcwd(), 'src', 'onegov')


def locale_file(module, lang):
    return f'{base}/{module}/locale/{lang}/LC_MESSAGES/onegov.{module}.po'


def open_file(path, mode='r'):
    with open(path, mode) as f:
        file = f.read()
    return file


def parse_entry(block):
    parts = block.split('msgstr ')
    return parts[0].replace('msgid ', ''), parts[1]


def blocks_from_file(src, lang):
    return re.split(r'\n\n', open_file(locale_file(src, lang)))


def parse_file(src, lang):
    src_dict = {}
    for block in blocks_from_file(src, lang):
        id_, value = parse_entry(block)
        src_dict[id_] = value
    return src_dict


def emtpy_value(value):
    return value == '""'


def fusion_po(src, target, lang, dry_run=False, overwrite=False):
    src_parsed = parse_file(src, lang)

    new_blocks = []
    for block in blocks_from_file(target, lang):
        ID, value = parse_entry(block)
        new_val = src_parsed.get(ID)

        if not new_val or emtpy_value(new_val):
            new_blocks.append(block)
            continue

        if emtpy_value(value) or overwrite:
            new_blocks.append(f'msgid {ID}msgstr {new_val}')
        else:
            new_blocks.append(block)

    if not dry_run:
        with open(locale_file(target, lang), 'w') as new:
            new.write('\n\n'.join(new_blocks))
    else:
        click.secho('\n\n'.join(new_blocks))


@click.command()
@click.option('--source', required=True)
@click.option('--target', required=True)
@click.option('--overwrite', is_flag=True, default=False)
@click.option('--dry-run', is_flag=True, default=False)
def apply_translations(source, target, overwrite, dry_run):
    """
    Use the source and target names of onegov modules to transfer
    translations that appear in both.

    Example: apply-translations --src org --target town6

    """
    langs = {
        f for f in os.listdir(f'{base}/{source}/locale')
        if not f.endswith('.pot')
    } & {
        f for f in os.listdir(f'{base}/{target}/locale')
        if not f.endswith('.pot')
    }

    for lang in langs:
        fusion_po(source, target, lang, dry_run, overwrite)


if __name__ == '__main__':
    apply_translations()
