#!/usr/bin/env bash
set -euo pipefail

SELF="$( cd "$(dirname "$0")" ; pwd -P )"
REPO="$(dirname "$SELF")"

# The following block ontains the Sentry Auth token to announce releases on
# sentry.io. This has been encrypted as follows:
#
# echo "my-token" | gpg --encrypt --armor \
#   --recipient patrick.bucher@seantis.ch \
#   --recipient fabian.reinhard@seantis.ch \
#   --recipient tobias.reinhard@seantis.ch \
#   --recipient marc.sommerhalder@seantis.ch \
#   --recipient chantal.trutmann@seantis.ch \
#   --recipient david.salvisberg@seantis.ch \
#   --recipient claudio.pilotti@seantis.ch \
#   --recipient cyrill.kuettel@seantis.ch
#
# Be sure to update `configure-sentry` below and update the comment above
# if the intended recipients change. You will also want to create a new
# token with only the permission "project:releases" at that point and invalidate the old one:
#
#   https://sentry.io/settings/account/api/auth-tokens/
#
SENTRY_TOKEN_ENCRYPTED="
-----BEGIN PGP MESSAGE-----

hQIMA8fKJfEbgaaMAQ/+LpjZy4DsLiJn461paOxBAYpO0y5t7NKNGZBaQvma8q9r
Wz3h9nYZ540CGoMGvjeQ1TEefzG3Bntdhn4NmlxdY+G0zZ/IiSxC6JJqw3h8c0WO
bdwjUV3Y0rW1bbHBs1Icku3tbGE2WYKqTh2GPnOKaQZFaZFFCDj0sRJ+60MfL1lG
LmTdfYsvXG2A/VwZ/Rug5Y5pjpujkVmzE/okYXEiz7DZhsWB7fLq1KIKZuWaDpaO
NRUJci89nXgka8jb0xdvya9wkhdFwKL1zGgpHUHDYsCIA+oVUpwl2RHJ+7ksnRnq
o76957QSWV3KmyOLLSsCKModdKoVc7DRrDJ1MqBxaGXQUs00AYlZ8rddUkCCEmCy
+3bxglrqThYr+S/NMpj+8LyQA2flnSyrEGCx6GXEfLY9qoe9ZfAGfTI9Ir1S/ecM
QszA7BW7INFsEVS9sQrxuwqb/Rr4JKHA+SBWeEA4XqKMbWsAABfC7osH78VEyKze
KGYUiUJXCJLih9mG1YjCoJQIKcLzFwbtHflee2apKN6zyMh2MolYkYjMZ5diNWUy
5ajonXBtWKy7ETXbmuVYTTPjOcHuHN2+mblI+e5472C3aBz4sVoLy11E9ZwYu2Jq
K7lyEZ3/ZghxHhKCgqLooDYsWqhyaJVw1I6deo3Wq0gAFRdEjfKbfDtJ/i1HRmWF
AQwDB8/veYppZwEBB/0d44XTnTQyb3S9/9KPrfGZZZoang5Z3Aa1VHke0KbknSgG
6GV+Ao5Ood7DDEIO1zGlyTUHRvscSXT/mZZFJN3zCFbHtAMP9S21Yi4CsgDwRZfQ
aAkV1CpNofD6t2v69BMV4QJXWDmuRoLqWHiXYfHr3hceU+/5YknnjpFJHLGB5OZ8
iZYC9d6f2OtA7jU1h5gtQho0wKJPmyAEAP6BEHNtYybH1hBOWk2sL7smPTbT/fW9
YmYkyf/Owtmc23vexe3MWruQYw6yw6KK/fGMbqG3xgobejTSPQ17Asz8QE2DxlwO
LtXGhhfz7tU+us6O8zsfd9PyOeTuW08sX1KhYkjIhQIMAzCQ2f+r7xQiAQ/+NoUe
vRMn6WcYBjUkIXpSMTApn8OjfQh86p+k05CWmJrE5jxpUAEF5rv6r81/9FHLsEGD
gcklCd2TRIepqK2v2Dn+TKvvUW+M15ROeLBOvycwEQpBmlE6ijGS4nR2vHm9LOIy
vSnkKSJO3rPwZUChqg0MQFVx3/vi/yaONg1OkdKrrMyxIKSqxAW85awjDTEt0U3e
I+4loaOU4o3GUCrbmYEssjcn2nozTQ1ryF7N6rxJ7vhEtO0KBJwP8h8TLTnT5t+o
Sg4Nb9l76JDcBr3wCXhheao8LA7maLuh3GHfoHUByAjpt+Qkf3mn+enykQ2zLUvi
GNiVT9xL1b+oIe96EXJCJ+pSppjYHNY0AGNE2yXHTRE42W759DT3bCaIF2Kbyhlm
QPV1Ub1oe5kN4tp4opt697GC7MS8fL5P5/rBnyV/NY+cHAgQfaep0635XxfO8YwI
dOk+R8hL103HvlPibX8J/WhUob88VlYhJyn5vnJsNYqb3/eUx3wRBDJ03S0hCTF3
rDvQe2dTSTGvlbfitgLFV+raiV1L5riB2AtgKUSmB8LIbv9ghwIB32G2ixRbBaYC
e9u7XL+69mr+DEK8DUG1sMm/IhxdStlNJc9YTbjO0kvga4KNsQJRsi58XeZptACh
VCNJ1y7fZpQhNVyOdJsGqfGKIKeCcGw/MxL/mwSFAgwD2aIEQK3XbQQBEACtN350
XKYggDhOM94HJysooVaEnjB/COxUgaS5HSB+2MXMNThLZ1oEq7b1gE31Ii9o3M2n
WjXB0I/Z2juwV9s+SQBSSd1A1EgSyHZoI/75HJOyvLgcGxO0r7tyO8p2Xz4dWne5
xMxZbhUfn6DHs/xL/5Bd4buSJe50qChTb7C51vgvImeXvFuOjsDkQ9+98YKSgeLS
bP1EX9dOkJ7J3cUdyXfrtSJtSqmlK6FL1k1NXNe8JiRXc8Rnjx3l2aaIB9t21t5b
CNQ770KIJhxiV4oIYnOvmo7QGUcsT9M9G3BOECSy+CWYUTpyFsFhOiBMRMDg/wuE
Gib6pBCip/E5hC2yz/s5xnGe3JDw9LWXrl5QLPyYq9hvkWNsB8FYRvisSKQnRoc1
PXp9wxtjwzCqykvMcIRzsIjEWq657OcaOKF7Vgsse0x5S5B/t7L9c38LS+qu8FvQ
a7Eex4BZ5zA1nzY2+uqjKlcIgNuzCpYzDt6KoxcKHFzJxCDFRNXjuQXT5y0DZhll
OiVFSg8Z/SidgLrFXS0Hze8OCWG7X6gE2cUF7DJzD/WLdB3BmTlZltUfSXvGKGs3
spcveFJNzbKWas4+FLIGv75CvJ3TYnqplXx9AP2RCcpOCMmuQh2/WxDajzKzh4I5
Ubcufgw1l10Bk5ucTo+m6C8JLhzGrxaqMk7U/4UCDAOY9mrL6rSNSAEQAIG8swnP
54Tox5LKMMwX367oKQ5QhchMUZjURe5hXvm0bUlXoRUWHfnNyvcE/h63GJ2Cpbdd
+smVUzg+5dD756TWaDrpEdRs9qBCN/r5Q02dNTbZxNKU/LHtlD2vi6RMVIeiEzTs
0m51z8PShChe6F1TRQfcIbxHZSmih7FwyzpvtSZEeKWt0kZg3tak7uCviAZimnmI
UwWULrrfFFOr3VScbnEC1aylk4J+omF50vfi9XQefWezdA9tXvp3fl2oZWFiUB4I
GMgJRDcRSoYbCpFxwfG4wFG8rX7zH83O4mDA1EJTPFr+SPS5JwuHO+0scj18ORYA
vosnj1mpLqQlKe/7sJ3nxcxO0CtHIFBW9GrX52dsB+iP6TZ4+DwPcvUG05Ytpz/Z
mvbVCy9YcJPnsAQ8RgJI5SM0XsVGq9bv0eleLLHpdITdUCDqlIl29ARmcE/ktxx1
3kdQhO0hRVyM8J86qH15Nwx2e123ZK7wVfYzS5ATeI5ZibQiJM7EXRxo0x0RpnzX
2u7qJ3JsNb7frz28vJ1V3dCMIrDZNqk/Aulqpxl2dtFxpS3h//h3mHwcBLxVX4L4
we/T19N0hBQclI/gDvxHi2+w03f6ODpe40mYgTgplPllvmMnZeCywnjLYTQxgQd8
H0T8pkEFBBteka/Kve+VpE/gC/UY53inrHC3hQEMA7tfQkCKWeaIAQf+O8+x2GhF
D18Jp73Ib4UzerjQ+ZtSzH9e7CcQ6Hyh197Aq52JtsXTP/4+966ORltahLsmGC8m
Ddugb4F5OGvSR/rIJgWhtAsy9iYer9bCgqaOArSfnoq8xmijE9NdzUrCpO8Jh44p
LSdMStgKoj9KRM82uu+g/7FTTz2ZRRVsZwthq7WQg/MyaZCMWVNjQEHQZlLFJcsI
xxMi3PqVfZQJ0yosbtLZsofPXFLLd0pQYEuI0GLT8TOHf8ac5fDp0oOqn1rPGhOd
hHgew0IJG3MahDdjzdUZXpPNTu3mfIvA9QjTVttOg4wkMCJj+JkPQe7HZkW+2c0t
EOcaz2MKhNcD0YUCDAPq87DK65y6qgEP/3w/n+3WKhFrd0+RhctqiYpQ4cXPOUNp
my6N0u28w2x7n341LxfjHcyLf5dE4tEbqiahFb0I7SIzbZ6T7zsjT5OBSLwDBbTe
d8Kut4TevDWK6/beze+6Woj36hLZSBbIWk8Bp2J5K+cvbb7z6PTvNhbiSxbuG4T/
/7nLZ0CQg/gXC59/nwhZ5tZL5oZd6Evu3zu2/yO3x88PX3PhqkFOf2ES9RuLoDGK
177wlX8EM0bG2N3PmLNsLJPUrUUhXc3M23CXe9ikpcJWTCCMzI50/7XCWrKUHGtd
ChyNGAJckmFM7yW6NrOUyQXcSz6deg2aoMJRsAY5UVGygOkryIvMW6PbVgdz+h/m
FrKR6sQKjAr2O3+Q5XPPuDPhMQEpHvRDWDvGYh1D8LnfHe4sASnd8ktBKvC+Jq8d
t1RTbQ3vFcxAcw0sfL03j9+35o8d4JfeO1T/vuQIvakg1TLtZ95jVTZK+6epJWYf
ylJXd+frIVJUl4ej1dn2+ag1p5fXDxp3qgMQFubTt4DYh+qqnptLSjlbsqLijoJZ
te8gAI8TEvowFPATogx3AgFcRHnV/JMCFuI2Nt3mKOhNonHhq0iguvPzMUnNyQlO
pgCOqdN2kB0erW7RS339z4N44NMv0QT98WAaT9g7o8Si6Sj1kJWNuG+62nw9OllV
5sWuq9RlLYomhQGMA7/IySjUDo4fAQv+PjiAvPyITzQRiSYXNGCkf5TH3l0c1TcR
imV5ZC+d4RKevc1prrax1wLN5Wx1hzwXXhaB5Scv8EpIiEWGm9Jo3FWRcVfa3ekc
jFNg0WIzlfElWoC41K1v9e75i+iKPTfrviYhllVPE/1PGjCAEOKdie+Y29UNPTkc
CWUcOPH3pbSpzFXDgEISW0LKOuDyckGw2pFMYo69ecOjBWFkLS7XwmbHhyT96q32
ekApuSSCcdaONxWPzQ19mbOVdcpVfiJUsqiKOhrQ4lvbjvO5uuBkHG7FExyKAXCy
96jqE0hwKgrfaTLzoMixv7mwDU1KYbu9TtgGgJhNEATADtDp9kHxtn3GlgSWEEOK
pOUxIGVywh3pJ3bVOHySXyf1PmH93hiwJbku+ZwbepDysH7S2sJSAmQJmx8tSSaM
+FStg/aoKnHidGQgxpVqcilFmHzdCSj2AAWtH5uJDTh5fzIV8aXRO4XkJREzK85V
Ch38ZGKseDuNBkE4ciPzh/lH7TRrDEfm0nYBxjBNFovJpfzoQNfmfMsp17TuFiN9
YR4/ZC8vPs4GJiQV3G6X5i8i6/dNU0dVYWz17OxCOJNHtC7uPbG/EHc03/yrgEu/
MeJbHiRKsOV4bdEVw4fVKm5KBjgtlUaUms2hO5KhjxXyJElNfT9BhlCrFcL+iK+G
=PNK6
-----END PGP MESSAGE-----
"

function configure-sentry() {
    SENTRY_AUTH_TOKEN="$(\
        echo "$SENTRY_TOKEN_ENCRYPTED" | gpg --decrypt --quiet
    )"

    export SENTRY_ORG="seantis-gmbh"
    export SENTRY_AUTH_TOKEN
}

function current-version() {
    git ls-remote --tags origin \
        | awk -F '/' '{print $NF}' \
        | sort --reverse --version-sort\
        | head -n 1
}

function announce-release-on-sentry-io() {
    local version="$1"
    local current_commit="$2"
    local previous_commit="$3"

    curl "https://sentry.io/api/0/organizations/${SENTRY_ORG}/releases/" \
        -X POST \
        -H "Authorization: Bearer ${SENTRY_AUTH_TOKEN}" \
        -H 'Content-Type: application/json' \
        -d "{
            \"version\": \"${version}\",
            \"refs\": [{
                \"repository\":\"OneGov/onegov-cloud\",
                \"commit\":\"${current_commit}\",
                \"previousCommit\":\"${previous_commit}\"
            }],
            \"projects\": [\"onegov-cloud\"]
        }"
}

function new-version() {
    local version
    version="$(current-version)"

    local year
    year="$(date +"%Y")"

    local build

    if echo "${version}" | grep "release-${year}" -q; then
        build="$(echo "${version}" | awk -F '.' '{print $NF}')"
    else
        build="0"
    fi

    echo "release-$year.$((build + 1))"
}

function release() {
    git fetch --quiet

    if ! git diff origin/master --exit-code --quiet; then
        echo "There are unpulled/unpushed remote changes, please update before release"
        exit 1
    fi

    if [[ "$(git branch --show-current)" != "master" ]]; then
        echo "A release can only be created on the master"
        exit 1
    fi

    current=$(current-version)
    new=$(new-version)
    short="${new/release-/}"

    echo "Releasing $new (previous: $current)"
    "$SELF"/changes "$new" > "$REPO/CHANGES.md"
    sed -i.bak "s/__version__.*/__version__ = '${short}'/g" src/onegov/core/__init__.py
    rm src/onegov/core/__init__.py.bak

    pushd "$REPO" > /dev/null
    git add CHANGES.md
    git add src/onegov/core/__init__.py
    git commit -m "Release $(new-version)"
    git tag "$(new-version)"
    git push
    git push --tags
    popd > /dev/null

    local previous_commit
    previous_commit="$(git rev-list -n 1 "$current")"

    local current_commit
    current_commit="$(git rev-parse --verify HEAD)"

    announce-release-on-sentry-io "onegov-cloud:${new}" "$current_commit" "$previous_commit"
}

configure-sentry
release
