#!/usr/bin/env bash
set -euo pipefail

SELF="$( cd "$(dirname "$0")" ; pwd -P )"
REPO="$(dirname "$SELF")"

# The following block ontains the Sentry token to announce releases on
# sentry.io. This has been encrypted as follows:
#
# echo "my-token" | gpg --encrypt --armor \
#   --recipient patrick.bucher@seantis.ch \
#   --recipient fabian.reinhard@seantis.ch \
#   --recipient tobias.reinhard@seantis.ch \
#   --recipient lukas.burkhard@seantis.ch
#
# Be sure to update `configure-sentry` below and update the comment above
# if the intended recipients change. You will also want to create a new
# token at that point and invalidate the old one.
#
SENTRY_TOKEN_ENCRYPTED="
-----BEGIN PGP MESSAGE-----

hQEMAyLmeAatF6VUAQgAokthDM+o/DIEpZyrQYjQsLapzhiX1ZQ8Dw/o4qF2Z9MA
wsXaQXrEBcBzy2fLace2tRWwH6trR/u2+a2vC9aKXjqyPoFtfwi6eUhwRJ26AyWE
UWzQ4Vrv3fmtDGiYEbcUwe8DKIHa86KrpCTuAc86ThAddaF9xOwqY/8XTMFqlPjf
7Uphrw3jts0FGvVMbjdvDHpKS2OM+5b/xj2q5A7cnkKyWrTSaG5hzWbjupiki1On
kN0WQFftiOtF5AYpdH59DV5h/jEEdJgG3FjRBaM/8n5Ws/tA9f2vVRQ5fAAf+sEo
qElbiHRKdpWdtb8YgphkgTaniFibwf2ikS1JhSFCoYUBDAMHz+95imlnAQEH/1R6
TlZ5buIUZhW3d+z2AwbgJIeL3WgCp9YSm14whrAcGuBjGHU8/fEIOtVtptD3GTfA
NHUrjGOaguJHriio32t78EQNNroWYZAxZBLMB131IDKnqpfYqzmt1mbOYDc65H3A
ShMaeBnEXlF8nyPNG3wlqM+pg7BmTdHa5j7ga7B+y4f97B/6T4oOI25Yi1Wm/Ox8
O7Dil+GWaHCLvbaUlO8YIEpx8pRe+AK3Y7LTGnWtbqFGqi2bluZw/Il9/5pEkXsD
7lHkwMjRA7ItdvTlcc5Wjx8g/QgspnxCk7uvSjiwX5pS8jToCMRNqlevxjOZ/y5H
TZYSG+4OMjCvItWJDGmFAgwDMJDZ/6vvFCIBEADF5UpN+8eP9fIptQxcmUGEzztK
5U77y0B7GI5YxLEt/j7/btyIzHCJvrV2jt48LrCG8mWLCq8BOJiRiapL1/I2IEj2
9mkAeqNv3WF2Jy3OaaTcBZNu9N/CUszj8vodDpbqccxj+yl1RqNEMBk1XcjQIE+D
+LtWDA79qG7qieWy+SuD7lJVCHtunexki+QbN2Tp53IQI61QFGQc63qa5irWvLDW
RkZCsww2qO3G6tESHYTxJXUHWXHylKhm7/eUsU6lfn3CuCHOz1CV6tFaEGZdfkMm
Otz/z04PDyiz+0L7F1kc4gD83zlIh1OtYKDEAug+Qbj9sPYg2y2h9mMfnGf9yXFS
dD61MWMiJnGTpxwesnp3NJCaMtdmhGLmPXVth1LF9lNVDqam3gskey0hvLFeBaAt
e79UV1i7e5AD5w49WLo++/k3WM+26c/GIKuztCiS2aNLrAtkb9BA/1UOQN0VYQFz
4HAI5FUoFLsjVPVtpJHdiDmiXQkTVnT9rIont1smtJAP7JZdvF0rhQ6lOnX81JV0
0v8l70KCAb2KmDD8brRiUJXXToG4wtDyKtCziHpABqV7tuWgyBXLYdBxiECkAVzh
I2jXtGSi/Rwx2rc3JrtNJ8yp71OMTfjX4IXexmCcCEhmXOqNoTai8O3zLkdDsGQo
3tce5ruI9h2uqfCchoUBjAM2Q094zxJCUQEL/iI+/q5LvziY3/6VsMbxDqLWVuaS
av+u15O9VvaeGJbshj3j0ZayO442mfnAWE89iOwd2fbmvJhLsQuPVbfw3TwnacGm
Xg7rgScRS2DZdILfM2qmg4h4W48MQFNE37zjkSuxh/Ucz08WX1RwJATLe2baJXRW
KuCKQ2Gd3zivqy7TZ6pHp6wwu2s8+FyVYa3V4mRYbnleY/cOkLIYwrC8mRyXaKWt
HyemwUz58jQasGSYjVpWSbnjiddr6Avz6iNqIvPQrAvPN2CdTZPfshDgAb5XCBl4
KaER23o+fhmIWAojJT1QSZ39YuXGD3VNJrNzyedY1UPqi0bbZgfdOMhkxd28O/Tw
EEfmMH7L6M0W6vmUJsJVuertZCsOWbuxxMnP6tofsmR321NIckyda4g1st4uvNar
qCyKYn+4HeGvVJpIl3ojwCL8bDyBdd4WNHDzU8il0Npd4Y0yzJgLNhvNJ/ZiI3np
92SttEOZ/vfBcMCjkjkVkfevFs37fXn1ZMncJ9JzAQuKwbPp/6jNHNIL+BuoobDG
vpgil7VgvKM4rlMqTeUyFj23zHCBt9Di2AVrJkRf/IpjFflW/hrRs40IkJWsaRIq
iESFCYk4YUS9wya5WIpoeEJuJO2ITwC7vhi0aHMluqoatUSsoPpQdo95LMkqchZ+
ag==
=BrJo
-----END PGP MESSAGE-----
"

function configure-sentry() {
    SENTRY_AUTH_TOKEN="$(\
        echo "$SENTRY_TOKEN_ENCRYPTED" | gpg --decrypt --quiet \
            --recipient patrick.bucher@seantis.ch \
            --recipient fabian.reinhard@seantis.ch \
            --recipient tobias.reinhard@seantis.ch \
            --recipient lukas.burkhard@seantis.ch \
    )"

    export SENTRY_ORG="seantis-gmbh"
    export SENTRY_AUTH_TOKEN
}

function current-version() {
    git ls-remote --tags origin \
        | awk -F '/' '{print $NF}' \
        | sort --reverse --version-sort\
        | head -n 1
}

function announce-release-on-sentry-io() {
    local version="$1"
    local current_commit="$2"
    local previous_commit="$3"

    configure-sentry
    curl "https://sentry.io/api/0/organizations/${SENTRY_ORG}/releases/" \
        -X POST \
        -H "Authorization: Bearer ${SENTRY_AUTH_TOKEN}" \
        -H 'Content-Type: application/json' \
        -d "{
            \"version\": \"${version}\",
            \"refs\": [{
                \"repository\":\"OneGov/onegov-cloud\",
                \"commit\":\"${current_commit}\",
                \"previousCommit\":\"${previous_commit}\"
            }],
            \"projects\": [\"onegov-cloud\"]
        }"
}

function new-version() {
    local version
    version="$(current-version)"

    local year
    year="$(date +"%Y")"

    local build

    if echo "${version}" | grep "release-${year}" -q; then
        build="$(echo "${version}" | awk -F '.' '{print $NF}')"
    else
        build="0"
    fi

    echo "release-$year.$((build + 1))"
}

function release() {
    git fetch --quiet

    if ! git diff origin/master --exit-code --quiet; then
        echo "There are unpulled/unpushed remote changes, please update before release"
        exit 1
    fi

    if [[ "$(git branch --show-current)" != "master" ]]; then
        echo "A release can only be created on the master"
        exit 1
    fi

    current=$(current-version)
    new=$(new-version)
    short="${new/release-/}"

    echo "Releasing $new (previous: $current)"
    "$SELF"/changes "$new" > "$REPO/CHANGES.md"
    sed -i.bak "s/__version__.*/__version__ = '${short}'/g" src/onegov/core/__init__.py
    rm src/onegov/core/__init__.py.bak

    pushd "$REPO" > /dev/null
    git add .
    git commit -m "Release $(new-version)"
    git tag "$(new-version)"
    git push
    git push --tags
    popd > /dev/null

    local previous_commit
    previous_commit="$(git rev-list -n 1 "$current")"

    local current_commit
    current_commit="$(git rev-parse --verify HEAD)"

    announce-release-on-sentry-io "onegov-cloud:${new}" "$current_commit" "$previous_commit"
}

release
