#!/usr/bin/env bash
set -euo pipefail

SELF="$( cd "$(dirname "$0")" ; pwd -P )"
REPO="$(dirname "$SELF")"

# The following block ontains the Sentry Auth token to announce releases on
# sentry.io. This has been encrypted as follows:
#
# echo "my-token" | gpg --encrypt --armor \
#   --recipient patrick.bucher@seantis.ch \
#   --recipient fabian.reinhard@seantis.ch \
#   --recipient tobias.reinhard@seantis.ch \
#   --recipient lukas.burkhard@seantis.ch \
#   --recipient marc.sommerhalder@seantis.ch
#
# Be sure to update `configure-sentry` below and update the comment above
# if the intended recipients change. You will also want to create a new
# token at that point and invalidate the old one.
#
SENTRY_TOKEN_ENCRYPTED="
-----BEGIN PGP MESSAGE-----

hQEMAyLmeAatF6VUAQf+NwUzy3pkyeMmtM8tQ7a63Hr7x/zsYrr2Amae1otnmkD/
4tzioGPFmtDkYfHtnShbuj1i/GtoeuhcdtQNnmBE+R0mVFH/i6c9JBbTt3rah5P5
CspRuPybHtcjr1f0vzuYNzl42CQ5JS+CpzlH5HxxXhcktKBdVWq2nGBKqGuaEsCN
/LPjZgs+HU+W5Q9XbROzDfYTpQhZHY8X86DexfRjDhVfBPNt9XNJQEmeGh1xJ711
F7DtsscBIvflwo0bnGNXYgQ/Xxw11PVZfzgWu2upbADCt6oqnhLm6Ok8fujDmMcZ
XyeCYR7JN9v1Y1NiUTbzh0DraJRpbukQYZUj7UagtoUBDAMHz+95imlnAQEH/096
Dqok42XbMyAb6z0L576X0g2zoCWlMU/Qz+YWJc419/aiwnaysJZJqwxXoFsgp12d
wzKD9dpWo0Lv3xaUtDRkRizZBFG/g6ddaXxwbtylyIXfJe7cXi7BNBQ9WT1osgRD
iXMfR9o2H8Em/rsnKjjj3h6/EQP7eafWxapt8qBpn/nqKSSHyKQCVOpTuwss3LxN
Qlv4RTVt7TAzpujznOxEZqidkLL9jWQHNPJ5Oa8ccJJPVQCho4W8qtEisMdkQr+l
RaVi7+F5qPRsw5h7VjnYW9mx9bOBPUovxrXjN+WTs8t2QLUvA4sHlYxH8UBoi+pB
J6HPxg4Ng1I6HUoQrkSFAgwDMJDZ/6vvFCIBEADE/yUMZCAhlkQww1bpt60DXaLC
Gv9uoCEhFaScn0SsKADbqBDcMeesD6yhSTN5jaKYmgLQ3kC/oRwO3WlI8fhaEvUB
caS9CpeE32y8EF2knkSicV7HKcl6yZKZjVyLq6xs3dnlcfCalZFn5CkrdVkeZ0zm
cEEO5waVgPoMYo9/EOT4OQo0e3HpFFHTTpFJTyRjz3Js+GgvJzIpu8zp2yNFYhp1
cystcCSbY3ajjpdFasnwUvACWgfMHC9rP7eTw6YOVo0gZxcqUXt4iftQhk++pIlo
2CARj7cMEPDaK4duuQnoxHsTh4lRr+vaq8sLXvRZqFfZz9Pu5lM3N67aqFDOK7+J
lfyE0KxgYYCwFlLZVKoHfnUKOblnmCdx1ibiKKzZCzjrAjv+Eax7qSdcuZJqY2Qt
2TNRmP7S1NMxSk4kNbzSTXeqB2XMeZndqUTdEVYzCjxbraxmA5VSgk/agXcpHUrU
R41dugEg+7HVR+6c+94zpbKAbPYJIFLK97H58oW5R0hsgKu5RagVNztX/XHfXgHN
Dvf/5DNC6f8Z61FGUNMP1TeAHLlLZ0S1NOfo8F47noXELPFmTwD2QqXJW8C37gBk
snhFepkFv7g2fhBlYm817OIemKw3VW7dMTNkn43MD6lZOBl9k9skHv2cs2t2OeJL
2faIkPy6GcGzILqT4oUBjAM2Q094zxJCUQEMAJD4xUPlsyDv//P2w52DwFe0fYi2
vmtA3hQVAMMn0KY4zGfDMBQGS0/5maRzW4jmqFKen3Mq0jhmFa/ASxbxiVObaWh1
1PNlAvWpaYiEQa4k8kM69OuQZ0dHlPt0RNWY9oMw8t6gzYoiClNziNS3aJJsmscH
mO9Q6HS6bkll1vtiZiHE3Jv06mMYcChNOLBRNIWI8v2Px8yoqv5bLSKIo0Io/nTg
7+Qj6OICvc4ljmSWJaAmOErM+hLN+ma57X/EvzRtgGgdOEBjlbwzQ1AGxMB188l4
Ue5rFdejQEnP6/HY2+OAe1sLoemPmE8ZItqA8FbWbIE3kXe2b2d6fk3QvlcwCFoC
p2clyL8aBTFjLq8RbI58CypfSr7jKkH4aXCHRnP7fb+fe14YoW+XxDfo918KpJiM
Ui04Gk70aSCR+MJtrXRQjUx8+OMNIhvhh9DfNHzHnQExvYB24nOZupKtp7C9W/sn
wfSa/7M3yrxEMd+0Uvt7AIKnfJHVg3DlyQiXSoUCDAPZogRArddtBAEP/AkFwkjR
liVwX/fZ2NuuCxjPiKi6o5IbLWRt6t6h+5sR5NB2fh+q0MXeAhEIIcudhrH6kCno
PGr8aFRTobG1PnmCHoQqs56T5jx5XIOxIDnUQaQX69MegjL4Xmi1coEgJ6/xskCU
pcURUvGgMzG1sfZajVWFsCAPvKPziSPooDdXCEdQcea7Jjn9N9dP69D31UaQ6RXQ
vWAm1gWl+ygD7NYq9X4/t5/hJ0TUs/eAAm3oerVsOcspprKwtskMNRCaF0V119kr
9IV1VbpkFVWDJSOPArDW6T50LGXdASqQLFifLjc2YSrrSU112CxhswL3F4ajKQ7o
ra7q6o8xtnWjKVzXZlQiaeEq6vrgCvN/RY6rNiUSTECXztBfK/LLqT00GbDwB9uC
qedNn6mUrRgxueUk/Bwpfu3LIO0TTYZMVGS9R9yH5+P3Mu5erwC6821EuMTDbpIk
c6NG9DuNmcQfeSNmvaRE4UIHVR6SW6paPpV0GhgIV4wDeTDNpeAyp+yEsRqZHtla
vECNZsID5k/Cwbh3/QAGqfmix9o8zzRcu6/SvLuGnLow+kx5ga3ve2VVQwdk06II
EuUT0E9GKJ/ASy3XPHxwmIloQdOGVU+21zBJn+jPDS8bwq1Osv4oDSQY2gEDNG3F
CMyFyYnb6JuM5zC5PVH1VRniJmxs4gXRV08q0ncBzIVzHboIlryB80AhdsNvwjQa
fLQO/gaK8+gNHI+yEDn1y85OHpsWlKSaA//2vVcGYIW/cRQEs7GPSidwaXZ0x13s
7CwwIchsNuDGiDT3VLPrixxLMe1MKdkNQS/SbzSfeWq/x7SnbcF/4mEGG73iLyDp
CLcXCA==
=GZYD
-----END PGP MESSAGE-----
"

function configure-sentry() {
    SENTRY_AUTH_TOKEN="$(\
        echo "$SENTRY_TOKEN_ENCRYPTED" | gpg --decrypt --quiet \
            --recipient patrick.bucher@seantis.ch \
            --recipient fabian.reinhard@seantis.ch \
            --recipient tobias.reinhard@seantis.ch \
            --recipient lukas.burkhard@seantis.ch \
            --recipient marc.sommerhalder@seantis.ch \
    )"

    export SENTRY_ORG="seantis-gmbh"
    export SENTRY_AUTH_TOKEN
}

function current-version() {
    git ls-remote --tags origin \
        | awk -F '/' '{print $NF}' \
        | sort --reverse --version-sort\
        | head -n 1
}

function announce-release-on-sentry-io() {
    local version="$1"
    local current_commit="$2"
    local previous_commit="$3"

    configure-sentry
    curl "https://sentry.io/api/0/organizations/${SENTRY_ORG}/releases/" \
        -X POST \
        -H "Authorization: Bearer ${SENTRY_AUTH_TOKEN}" \
        -H 'Content-Type: application/json' \
        -d "{
            \"version\": \"${version}\",
            \"refs\": [{
                \"repository\":\"OneGov/onegov-cloud\",
                \"commit\":\"${current_commit}\",
                \"previousCommit\":\"${previous_commit}\"
            }],
            \"projects\": [\"onegov-cloud\"]
        }"
}

function new-version() {
    local version
    version="$(current-version)"

    local year
    year="$(date +"%Y")"

    local build

    if echo "${version}" | grep "release-${year}" -q; then
        build="$(echo "${version}" | awk -F '.' '{print $NF}')"
    else
        build="0"
    fi

    echo "release-$year.$((build + 1))"
}

function release() {
    git fetch --quiet

    if ! git diff origin/master --exit-code --quiet; then
        echo "There are unpulled/unpushed remote changes, please update before release"
        exit 1
    fi

    if [[ "$(git branch --show-current)" != "master" ]]; then
        echo "A release can only be created on the master"
        exit 1
    fi

    current=$(current-version)
    new=$(new-version)
    short="${new/release-/}"

    echo "Releasing $new (previous: $current)"
    "$SELF"/changes "$new" > "$REPO/CHANGES.md"
    sed -i.bak "s/__version__.*/__version__ = '${short}'/g" src/onegov/core/__init__.py
    rm src/onegov/core/__init__.py.bak

    pushd "$REPO" > /dev/null
    git add CHANGES.md
    git add src/onegov/core/__init__.py
    git commit -m "Release $(new-version)"
    git tag "$(new-version)"
    git push
    git push --tags
    popd > /dev/null

    local previous_commit
    previous_commit="$(git rev-list -n 1 "$current")"

    local current_commit
    current_commit="$(git rev-parse --verify HEAD)"

    announce-release-on-sentry-io "onegov-cloud:${new}" "$current_commit" "$previous_commit"
}

release
