cache: pip

matrix:
  include:
    - language: python
      python: "3.6"
      env: TOXENV=py36

    - language: python
      python: "3.6"
      env: TOXENV=pep8

addons:
    postgresql: "9.6"
    apt:
      packages:
        - libgnutls28-dev
        - libev-dev

install:
    - pip install tox
    - if [ "$TOXENV" = 'py36' ]; then pip install coveralls; fi

script:
    - tox -e $TOXENV

after_success:
    - if [ "$TOXENV" = 'py36' ]; then coveralls; fi

deploy:
    provider: pypi
    distributions: "sdist bdist_wheel"
    user: seantis
    password:
        secure: EeNcMxJJlbhaQOSSd2YbYFI62rEMLr+KhYAb1CWtiErnUJwudT4a7pgqyKZ9YXX8fv+H4IzSxC70KPJUQb7vXv1xLRPSsgkM7ulQkaAObGn4lNX1ki+73+2Aru6L5pIadO1FbJ05OW0198lPZlG5qRGRvxLZ+B6jzaRMJ+6GqD0=
    on:
        tags: true
        condition: $TOXENV = py36
